stage:
  before:
    - export SECRET_KEY_BASE=abc
    - bundle exec rake sandbox
    - echo 'Rails.logger = Logger.new(STDOUT)' > sandbox/config/initializers/logger_stdout.rb
    - cd sandbox
    - ln -sf $PWD/public $PWD/../public

  run:
    # workdir is sandbox
    - bundle exec rails server

  database:
    - echo "skip database stage. rake sandbox already did everything"

config:
  database: postgresql
  services:
    - postgresql
